class TestPrepareRunError:
    def test_prepare_run_error(self):
        pass
